import { readFileSync, existsSync } from "node:fs";

const requiredFiles = ["index.html", "styles.css", "src/main.js", "src/characterCreation.js", "BLUEPRINT.md", "README.md", ".nojekyll", "docs/CHARACTER_CREATION_BLUEPRINT.md", "docs/QUEST_COMPASS_PROPOSAL.md", "docs/BLUEPRINT_CLOSURE_LOG.md", "docs/NEXT_SLICE_CONTRACT.md"];
const missing = requiredFiles.filter((file) => !existsSync(file));
if (missing.length) fail(`Missing files: ${missing.join(", ")}`);

const main = readFileSync("src/main.js", "utf8");
const expansions = readFileSync("src/expansionBlueprints.js", "utf8");
const characterCreation = readFileSync("src/characterCreation.js", "utf8");
const formMastery = readFileSync("src/formMastery.js", "utf8");
const blueprint = readFileSync("BLUEPRINT.md", "utf8");
const html = readFileSync("index.html", "utf8");
const readme = readFileSync("README.md", "utf8");
const pkg = readFileSync("package.json", "utf8");
const closureLog = readFileSync("docs/BLUEPRINT_CLOSURE_LOG.md", "utf8");
const sliceContract = readFileSync("docs/NEXT_SLICE_CONTRACT.md", "utf8");

check(/class Rng/.test(main), "deterministic RNG class exists");
check(/snap\(\)\s*{\s*return { seed: this\.seed, count: this\.count }/.test(main), "RNG save snapshot stores seed and count");
check((main.match(/"[^"]+",/g) || []).filter((m) => blueprint.includes(m.slice(1, -2))).length >= 20, "objective text overlaps blueprint");
check((main.match(/const objectives = \[/) && objectiveCount(main) >= 45), "at least 45 objectives are implemented");
check(!/Figurine Tactics|startFigurineBattle|showFigurineCollection|figurineDamage|figurinesBtn|data-practice-figures/.test(main + html), "figurine tactics is removed from gameplay");
check(/startAuraForge/.test(main), "aura forge minigame exists");
check(!/startSkyCourier|Sky Courier|Courier Token|updateCourierObjects|courierObjectX/.test(main + html), "standalone courier minigame is removed from gameplay");
check(/function updateFlightHazards/.test(main), "flight hazards exist");
check(/function sfx/.test(main) && /function updateMusic/.test(main), "procedural audio exists");
check(/function saveGame/.test(main) && /function loadGame/.test(main), "save and load exist");
check(/destructibles/.test(main), "destructible environments exist");
check(/weatherDamageModifier/.test(main), "weather combat modifier exists");
check(/addEventListener\("gamepadconnected"/.test(main) && /function pollGamepad/.test(main), "controller support exists");
check((expansions.match(/^  blueprint\(/gm) || []).length === 20, "20 expansion blueprints exist");
check((expansions.match(/\["/g) || []).length === 100, "each expansion blueprint has five stages");
check(!/showExpansionBlueprints/.test(main) && !/completeBlueprintStage/.test(main), "blueprints are not gameplay UI or rewards");
check(!/blueprintsBtn/.test(html) && !/roadmap/.test(main), "blueprints are not player controls");
check(/<script type="module" src="src\/main\.js">/.test(html) && /<link rel="stylesheet" href="styles\.css"/.test(html), "cycle 15 static root is closed");
check(/https:\/\/pappydapimp69\.github\.io\/dbh-rpg\//.test(readme), "cycle 15 hosted link is closed");
check(!/"dependencies"\s*:/.test(pkg) && !/"devDependencies"\s*:/.test(pkg), "cycle 15 offline shape is closed");
check(/"check": "node scripts\/check\.mjs"/.test(pkg) && existsSync("scripts/check.mjs"), "cycle 19 syntax gate is closed");
check(/codexBtn/.test(html) && /function showCodex/.test(main), "cycle 16 codex UI is closed");
check(/factions: \[/.test(main) && /Ember League/.test(main) && /Quiet Shrine/.test(main) && /Rift Syndicate/.test(main), "cycle 16 faction notes are closed");
check(/regions: \[/.test(main) && /Metro Crater/.test(main) && /Moonfall Citadel/.test(main), "cycle 16 region notes are closed");
check(/techniques: \[/.test(main) && /Meteor Rush/.test(main) && /Quiet Pulse/.test(main), "cycle 16 technique notes are closed");
check(/bosses: \[/.test(main) && /Crown Engine/.test(main) && /Eclipse Heir/.test(main), "cycle 16 boss notes are closed");
check(/function train/.test(main) && /grantXp\(firstMiraLesson \? 16 : 12, "training"\)/.test(main), "cycle 17 mentor training is closed");
check(/function applyWeatherTrainingBonus/.test(main) && /Thunderstorm/.test(main) && /completeObjective\(32\)/.test(main), "cycle 17 weather training is closed");
check(/gainFormMastery/.test(main) && /weather training/.test(main) && /species\.id === "starforged"/.test(main), "cycle 17 form mastery is closed");
check(/function completeHiddenTrial/.test(main) && /hiddenTrialsCompleted/.test(main) && /Quiet Pulse resonance/.test(main), "cycle 17 hidden trials are closed");
check(/function applyBranchBonus/.test(main) && /factionReputation/.test(main) && /Tournament Pass/.test(main) && /Shrine Seal/.test(main), "cycle 18 faction bonus is closed");
check(/function finalRouteStatus/.test(main) && /Final route:/.test(main), "cycle 18 quest echo is closed");
check(/function recordBossOutcome/.test(main) && /bossOutcomes/.test(main) && /Outcome:/.test(main), "cycle 18 boss outcome is closed");
check(/Crown Engine outcome recorded/.test(main) && /completeObjective\(50\)/.test(main), "cycle 18 final route is closed");
check(/function serializeSave/.test(main) && /schema/.test(main) && /rng: state\.rng\.snap/.test(main), "cycle 2 schema review is closed");
check(!/completedBlueprintStages/.test(main) && !/activeBlueprint/.test(main), "cycle 2 blueprint progress stays internal");
check(/exportBtn/.test(readFileSync("index.html", "utf8")) && /importBtn/.test(readFileSync("index.html", "utf8")) && /showExportSave/.test(main) && /showImportSave/.test(main), "cycle 2 export path is closed");
check(/function parseSave/.test(main) && /Save data is not valid JSON/.test(main) && /function hydrateSave/.test(main), "cycle 2 load guard is closed");
check(/serializeSave/.test(main) && /parseSave/.test(main) && /hydrateSave/.test(main) && /persist\(\)/.test(main), "cycle 2 round trip path is closed");
check(/inputMap\s*=\s*{[\s\S]*interact:[\s\S]*strike:[\s\S]*blast:[\s\S]*guard:[\s\S]*dodge:[\s\S]*form:[\s\S]*forge:[\s\S]*quest:[\s\S]*species:/m.test(main), "cycle 1 control audit is closed");
check(!/courier: \[/.test(main), "courier no longer consumes a gameplay input");
check(/function actionPressed/.test(main) && /function techPressed/.test(main), "cycle 1 action vocabulary is centralized");
check(/function handleModalInput/.test(main) && /gamepadPressed\("padB"\)/.test(main), "cycle 1 modal navigation is closed");
check(/showControls/.test(main) && /Shift\/RT dodge/.test(main) && /Controller connected/.test(main), "cycle 1 prompt cleanup is closed");
check(/z\.flight \? 190 : 128/.test(main) && /function updateFlightHazards/.test(main) && /Wind.*flight routes speed up/.test(main), "cycle 1 flight tuning is closed");
check((characterCreation.match(/id: "/g) || []).length >= 7, "at least seven playable species exist");
check(/growth:/.test(characterCreation) && /xpRate/.test(characterCreation), "species XP growth data exists");
check(/passives:/.test(characterCreation) && /active:/.test(characterCreation), "species passives and active abilities exist");
check(/showCharacterCreator/.test(main) && /data-species/.test(main), "character creator species UI exists");
check(/applySpeciesToPlayer/.test(main) && /useSpeciesAbility/.test(main), "species stats and active ability logic exists");
check((formMastery.match(/id: "/g) || []).length >= 6, "form mastery catalog exists");
check(/getFormMasteryRank/.test(formMastery) && /nextFormMasteryTarget/.test(formMastery), "form mastery rank helpers exist");
check(/gainFormMastery/.test(main) && /showForms/.test(main), "form mastery gameplay and UI exist");
check(/showStartScreen/.test(main) && /startNewGame/.test(main), "basic start and new game flow exists");
check(/getInteractionHint/.test(main), "interaction hint exists");
check(/No enemy in striking range/.test(main) && /No target for the blast/.test(main), "basic combat miss feedback exists");
check(/openingArcDefaults/.test(main) && /beginOpeningTraining/.test(main), "opening training arc state exists");
check(/showStarterTechniqueChoice/.test(main) && /starterTechniques/.test(main), "starter technique choice exists");
check(/mira-trial/.test(main) && /Sparring Drone/.test(main), "opening sparring fights exist");
check(/openingArcLine/.test(main) && /drawOpeningMarker/.test(main), "opening arc guidance exists");
check(/addFloatingText/.test(main) && /drawFloaters/.test(main), "combat feedback floaters exist");
check(/function dodge/.test(main) && /resolveEnemyAttack/.test(main), "combat dodge and enemy attack resolution exist");
check(/enemyAttackPeriod/.test(main) && /enemyAttackName/.test(main), "enemy telegraph timing exists");
check(/perfectGuards/.test(main) && /cleanDodges/.test(main) && /bestCombo/.test(main), "combat mastery stats exist");
check(/screenShake/.test(main) && /heavyHit/.test(main) && /warning/.test(main), "combat impact feedback exists");
check(/combatHudLine/.test(main) && /guard or dodge/.test(main), "combat readability HUD exists");
check(/const questArcs = \[/.test(main) && (main.match(/summary: "/g) || []).length >= 6, "quest arcs exist");
check(/const objectiveTargets = {/.test(main) && /Dust Barrens gate/.test(main), "objective target metadata exists");
check(/currentQuestTarget/.test(main) && /questCompassLine/.test(main), "quest compass resolver exists");
check(/currentQuestWaypoint/.test(main) && /nextZoneToward/.test(main) && /Route to/.test(main), "quest compass routes across zones");
check(/drawQuestCompass/.test(main) && /drawCompassRing/.test(main), "quest compass visuals exist");
check(/Next action:/.test(main) && /toward \$\{target\.finalTarget\.label\}/.test(main), "quest compass action copy exists");
check(/Campaign Arcs/.test(main) && /currentQuestArc/.test(main), "quest log groups campaign arcs");
check(/Branch: \$\{state\.branch\}/.test(main) && /function chooseBranch/.test(main) && /branchBonusApplied/.test(main), "cycle 3 branch echoes are closed");
check(/Hidden mentor/.test(main) && /activeNpcs/.test(main) && /role === "hidden"/.test(main), "cycle 3 hidden leads are closed");
check(/function rewardObjectiveMilestone/.test(main) && /Objective.*milestone/.test(main) && /completeObjective\(index\)[\s\S]*rewardObjectiveMilestone\(index\)/.test(main), "cycle 3 completion rhythm is closed");
check(/function drawTileAccent/.test(main) && /tile === "sand"/.test(main) && /tile === "shrine"/.test(main), "cycle 4 tile accents are closed");
check(/function damageDestructible/.test(main) && /fell out/.test(main) && /grantXp\(4, "destruction"\)/.test(main), "cycle 4 destruction rewards are closed");
check(/landmark: "Crater Clocktower"/.test(main) && /function drawLandmark/.test(main), "cycle 4 landmark names are closed");
check(/function routeMemoryLine/.test(main) && /Route from/.test(main), "cycle 4 route memory is closed");
check(/const techniques = \[[\s\S]*sp:[\s\S]*range:[\s\S]*requires:[\s\S]*area:[\s\S]*reveal:/m.test(main), "cycle 5 technique roles are closed");
check(/updateEncounterPhase/.test(main) && /drawEncounterBanner/.test(main) && /attackPeriod/.test(main), "cycle 5 boss pressure is closed");
check(/function guard/.test(main) && /perfectGuard/.test(main) && /cleanDodges/.test(main), "cycle 5 guard value is closed");
check(/weatherDamageModifier/.test(main) && /weatherSummary/.test(main), "cycle 5 weather synergy is closed");
check(/unlock:/.test(formMastery) && /perks:/.test(formMastery) && /drain:/.test(formMastery), "cycle 6 form copy is closed");
check(/drainForm/.test(main) && /Drain \$\{form\.drain\}/.test(main), "cycle 6 drain readability is closed");
check(/unlockForm\("Flare"\)/.test(main) && /unlockForm\("Storm"\)/.test(main) && /unlockForm\("Iron Spirit"\)/.test(main) && /effect\.form/.test(main), "cycle 6 unlock routes are closed");
check(/drawPlayer/.test(main) && /form\.color/.test(main) && /p\.form === "Base" \? 2 : 5/.test(main), "cycle 6 visual aura is closed");
check(/function isNight/.test(main) && /function activeNpcs/.test(main) && /role === "shop" && isNight/.test(main), "cycle 7 schedule rules are closed");
check(/function train/.test(main) && /firstMiraLesson/.test(main) && /Spirit restored/.test(main), "cycle 7 mentor value is closed");
check(/hidden-mentor/.test(main) && /foundHiddenMentor/.test(main) && /role === "hidden"/.test(main), "cycle 7 hidden NPCs are closed");
check(/loot: \[/.test(main) && /destructibles: \[/.test(main) && /fell out/.test(main), "cycle 8 loot table is closed");
check(/function showShop/.test(main) && /theme === "water"/.test(main) && /Training Capsule/.test(main), "cycle 8 shop identity is closed");
check(/const itemEffects = {/.test(main) && /function applyItem/.test(main) && /effect\.skill/.test(main) && /effect\.form/.test(main), "cycle 8 item effects are closed");
check(/rewardObjectiveMilestone/.test(main) && /grantXp\(enemy\.xp/.test(main) && /state\.player\.money \+= enemy\.boss \? 40 : 8/.test(main), "cycle 8 reward scale is closed");
check(/Rare Training Capsule/.test(main) && /Complete Barrens sparring drill/.test(main), "cycle 9 has been pruned into training-focused rewards");
check(!/figurine|Figurine/.test(main + html), "cycle 9 collectible tactics code stays out of gameplay files");
check(/startAuraForge/.test(main) && /const accuracy = 1 - Math\.abs\(Math\.sin\(minigame\.pulse\)\)/.test(main), "cycle 10 timing loop is closed");
check(/Reward bands: 56\+ Polished Aura Charm/.test(main) && /minigame\.score > 55 \? "Polished Aura Charm" : "Warm Charm"/.test(main), "cycle 10 reward bands are closed");
check(/Misses still produce a lesser upgrade/.test(main) && /state\.player\.inventory\.push\(reward\)/.test(main), "cycle 10 failure softness is closed");
check(/accuracy > 0\.7 \? "success" : "fail"/.test(main), "cycle 10 audio feedback is closed");
check(/function updateFlightHazards/.test(main) && /storm-mine/.test(main) && /completeObjective\(31\)/.test(main), "cycle 11 is retained as traversal flight hazards");
check(/Cross first flight route/.test(main) && /Sky Route/.test(main), "cycle 11 route objective is traversal-focused");
check(/rain: \[/.test(main) && /wind: \[/.test(main) && /thunder: \[/.test(main) && /snow: \[/.test(main), "cycle 12 SFX coverage is closed");
check(/function updateMusic/.test(main) && /theme = encounter\?\.boss/.test(main) && /audio\.musicGain/.test(main), "cycle 12 music layers are closed");
check(/function weatherSfx/.test(main) && /sfx\(weatherSfx\(state\.weather\)\)/.test(main), "cycle 12 weather sound is closed");
check(/audioSettings/.test(main) && /function showAudioSettings/.test(main) && /data-audio/.test(main), "cycle 12 volume future is closed");
check(/musicGain/.test(main) && /sfxGain/.test(main) && /weatherGain/.test(main) && /applyAudioSettings/.test(main), "cycle 12 audio smoke is closed");
check(/#hud[\s\S]*width: min\(460px/.test(readFileSync("styles.css", "utf8")) && !/#panel/.test(readFileSync("styles.css", "utf8")), "cycle 13 readable panels are closed");
check(/interact: \[" ", "Enter", "padA"\]/.test(main) && /strike: \["j", "padX"\]/.test(main), "cycle 13 input redundancy is closed");
check(/handleModalInput/.test(main) && /focus\(\)/.test(main) && /click\(\)/.test(main), "cycle 13 modal focus is closed");
check(/Branch:/.test(main) && /weatherSummary/.test(main) && /guard or dodge/.test(main), "cycle 13 color meaning is closed");
check(/sx = Math\.floor\(camera\.x \/ TILE\)/.test(main) && /ex = sx \+ Math\.ceil\(innerWidth \/ TILE\) \+ 2/.test(main), "cycle 14 draw budget is closed");
check(/if \(state\.maps\[id\]\) return state\.maps\[id\]/.test(main), "cycle 14 generated map cache is closed");
check(/createOscillator/.test(main) && /function sfx/.test(main) && /function updateMusic/.test(main), "cycle 14 audio budget is closed");
check(/function updateHud/.test(main) && !/ui\.objectivePanel\.innerHTML/.test(main) && !/ui\.actionPanel\.innerHTML/.test(main) && !/ui\.log\.innerHTML/.test(main), "cycle 14 DOM budget is closed");
check(/actionHints/.test(html) && /function actionHintRows/.test(main) && /Start/.test(main) && /Shift/.test(main), "bottom-right action hints exist");
check(Array.from({ length: 20 }, (_, i) => `## Cycle ${i + 1}:`).every((heading) => closureLog.includes(heading)), "cycle 20 production smoke sees all cycles closed");
check(/Query Brain/.test(sliceContract) && /focused external research/.test(sliceContract) && /npm\.cmd run check/.test(sliceContract), "cycle 20 authoring loop is closed");
check(/Data Boundaries/.test(sliceContract) && /src\/expansionBlueprints\.js`: internal agent backlog only/.test(sliceContract), "cycle 20 data boundaries are closed");

console.log("Smoke checks passed.");

function objectiveCount(source) {
  const block = source.match(/const objectives = \[([\s\S]*?)\];/);
  if (!block) return 0;
  return (block[1].match(/^\s*"/gm) || []).length;
}

function check(condition, message) {
  if (!condition) fail(message);
}

function fail(message) {
  console.error(`Smoke check failed: ${message}`);
  process.exit(1);
}
