export const baseStats = {
  hp: 100,
  sp: 80,
  power: 1,
  guard: 1,
  speed: 1,
  focus: 1,
  luck: 1,
};

export const characterSpecies = [
  {
    id: "terran",
    name: "Terran",
    archetype: "balanced martial artist",
    description: "Adaptable fighters with steady growth, strong item use, and reliable training gains.",
    stats: { hp: 0, sp: 0, power: 0, guard: 0, speed: 0, focus: 1, luck: 1 },
    growth: { hp: 12, sp: 8, powerEvery: 4, xpRate: 1 },
    passives: ["Training lessons grant +15% XP.", "Consumables restore 10% more HP and SP."],
    active: { name: "Second Wind", cost: 18, effect: "Restore spirit and briefly raise focus after taking damage." },
    affinity: "Learns hybrid techniques one level earlier.",
    startingItems: ["Rice Ball", "Training Wraps"],
    auraBias: "#62d6ff",
  },
  {
    id: "starforged",
    name: "Starforged",
    archetype: "high-risk battle prodigy",
    description: "Explosive warriors who grow fastest through boss fights and low-health comebacks.",
    stats: { hp: 8, sp: -4, power: 2, guard: -1, speed: 1, focus: 0, luck: 0 },
    growth: { hp: 14, sp: 7, powerEvery: 3, xpRate: 1.12 },
    passives: ["Deal +12% damage below 40% HP.", "Boss victories grant +20% XP."],
    active: { name: "Battle Surge", cost: 22, effect: "Spend spirit to raise power until the next hit lands." },
    affinity: "Flare Form drains 15% slower.",
    startingItems: ["Spirit Tea"],
    auraBias: "#ffd166",
  },
  {
    id: "verdant",
    name: "Verdant",
    archetype: "regenerative guardian",
    description: "Calm, durable mystics with strong guard, regeneration, and hidden-technique perception.",
    stats: { hp: 24, sp: 6, power: -1, guard: 2, speed: -1, focus: 1, luck: 0 },
    growth: { hp: 18, sp: 9, powerEvery: 5, xpRate: 1.06 },
    passives: ["Regenerate HP slowly when out of combat.", "Hidden mentors appear during more hours."],
    active: { name: "Rootguard", cost: 16, effect: "Brace in place and reduce incoming damage heavily." },
    affinity: "Iron Spirit unlock checks are easier.",
    startingItems: ["Herb Bundle"],
    auraBias: "#64e690",
  },
  {
    id: "bioarc",
    name: "Bio-Arc",
    archetype: "precision evolver",
    description: "Sleek energy specialists with high speed, focused blasts, and rare evolution items.",
    stats: { hp: -6, sp: 14, power: 1, guard: -1, speed: 2, focus: 1, luck: 0 },
    growth: { hp: 10, sp: 12, powerEvery: 4, xpRate: 1.08 },
    passives: ["Charged blasts cost 10% less spirit.", "Flight route loot glints from farther away."],
    active: { name: "Prism Lance", cost: 20, effect: "Fire a piercing line blast that cracks fragile terrain." },
    affinity: "Storm Form damage bonus is stronger in bad weather.",
    startingItems: ["Weather Charm"],
    auraBias: "#f4f7fb",
  },
  {
    id: "majinite",
    name: "Majinite",
    archetype: "chaotic resilient trickster",
    description: "Elastic fighters with strange recovery, high luck, and unpredictable technique rewards.",
    stats: { hp: 16, sp: 4, power: 0, guard: 1, speed: -1, focus: -1, luck: 3 },
    growth: { hp: 16, sp: 10, powerEvery: 4, xpRate: 1.1 },
    passives: ["Destructibles have a higher chance to drop food.", "Status effects expire faster."],
    active: { name: "Elastic Rebound", cost: 14, effect: "Bounce backward, heal a little, and counter the nearest enemy." },
    affinity: "Eclipse Break backlash is reduced.",
    startingItems: ["Rice Ball", "Spirit Tea"],
    auraBias: "#b185ff",
  },
  {
    id: "android",
    name: "Android",
    archetype: "steady reactor fighter",
    description: "Engineered combatants with consistent spirit recovery and slower emotional growth.",
    stats: { hp: 10, sp: 18, power: 0, guard: 1, speed: 0, focus: 2, luck: -1 },
    growth: { hp: 12, sp: 13, powerEvery: 5, xpRate: 0.94 },
    passives: ["Spirit regenerates during guard.", "Weather movement penalties are reduced."],
    active: { name: "Reactor Guard", cost: 0, effect: "Convert a blocked hit into spirit." },
    affinity: "Technique costs are stable during form drain.",
    startingItems: ["Polished Aura Charm"],
    auraBias: "#ff5a66",
  },
  {
    id: "celestial",
    name: "Celestial",
    archetype: "late-blooming spirit adept",
    description: "Rare adepts who level slowly but gain exceptional focus, form control, and hidden lore routes.",
    stats: { hp: -8, sp: 20, power: -1, guard: -1, speed: 1, focus: 3, luck: 1 },
    growth: { hp: 9, sp: 15, powerEvery: 6, xpRate: 0.88 },
    passives: ["Forms drain 10% slower.", "Mentor training can reveal extra lore."],
    active: { name: "Still Star", cost: 24, effect: "Freeze form drain for a short moment." },
    affinity: "Solar Apex unlocks with fewer mastery fragments.",
    startingItems: ["Shrine Seal"],
    auraBias: "#fff1a6",
  },
];

export const characterCreationBlueprint = {
  title: "Character Creation Blueprint",
  stages: [
    "Race/species model",
    "Stats and XP growth",
    "Special abilities and passives",
    "Creator UI and save integration",
    "Documentation and validation",
  ],
};

export function getSpeciesById(id) {
  return characterSpecies.find((species) => species.id === id) || characterSpecies[0];
}
