export const expansionBlueprints = [
  blueprint(1, "Input And Comfort Pass", "Make long sessions easier to control and read.", [
    ["Control Audit", "Map keyboard, controller, and modal input into one action vocabulary.", "Focus Grid"],
    ["Prompt Cleanup", "Keep on-screen prompts short and current across devices.", "Guide Tag"],
    ["Modal Navigation", "Make every menu reachable without a mouse.", "Menu Token"],
    ["Flight Tuning", "Tune analog flight movement and route hazards.", "Sky Token"],
    ["Regression Pass", "Add smoke coverage for the input surface.", "Check Token"],
  ]),
  blueprint(2, "Save And Continuity Pass", "Make long RPG progress feel persistent and recoverable.", [
    ["Schema Review", "Audit saved state for new flags and expansion progress.", "Archive Mark"],
    ["Blueprint Progress", "Store completed expansion stages in save data.", "Planner Mark"],
    ["Export Path", "Define export/import expectations for later save slots.", "Vault Note"],
    ["Load Guard", "Patch compatibility defaults for older saves.", "Repair Note"],
    ["Round Trip", "Smoke-test save-related surfaces.", "Continuity Token"],
  ]),
  blueprint(3, "Quest Density Pass", "Make the 55-objective campaign easier to follow.", [
    ["Arc Labels", "Group objectives into early, mid, late, and postgame arcs.", "Quest Ribbon"],
    ["Branch Echoes", "Surface faction consequences in the quest log.", "Faction Note"],
    ["Hidden Leads", "Tie hidden technique clues to current zone and time.", "Secret Note"],
    ["Completion Rhythm", "Reward meaningful stage completion with XP and coins.", "Pace Token"],
    ["Quest Smoke", "Guard minimum objective count and quest UI hooks.", "Quest Token"],
  ]),
  blueprint(4, "World Texture Pass", "Make maps feel less like placeholders.", [
    ["Tile Accent", "Add visual accents to generated terrain by zone theme.", "Terrain Chip"],
    ["Destruction Rewards", "Tune breakable objects into loot and discovery beats.", "Rubble Chip"],
    ["Landmark Names", "Give regions stronger identity in UI and logs.", "Map Pin"],
    ["Route Memory", "Make travel messages reinforce where the player is going.", "Route Pin"],
    ["World Smoke", "Guard the core world content surface.", "World Token"],
  ]),
  blueprint(5, "Combat Feel Pass", "Sharpen action RPG combat readability.", [
    ["Technique Roles", "Clarify what each technique is for.", "Technique Card"],
    ["Boss Pressure", "Make boss alerts and rewards more legible.", "Boss Card"],
    ["Guard Value", "Keep guard useful in encounters and controller play.", "Guard Card"],
    ["Weather Synergy", "Keep form/weather bonuses visible.", "Storm Card"],
    ["Combat Smoke", "Guard combat and weather modifier hooks.", "Combat Token"],
  ]),
  blueprint(6, "Transformation Identity Pass", "Make forms feel like distinct builds.", [
    ["Form Copy", "Clarify form names, costs, and unlocks.", "Aura Page"],
    ["Drain Readability", "Surface form drain through HUD language.", "Drain Page"],
    ["Unlock Routes", "Tie forms to bosses, items, and faction rewards.", "Unlock Page"],
    ["Visual Aura", "Keep form visuals distinct in ground and flight maps.", "Glow Page"],
    ["Form Smoke", "Guard transformation data and unlock hooks.", "Form Token"],
  ]),
  blueprint(7, "NPC And Schedule Pass", "Make towns and mentors feel alive offline.", [
    ["Schedule Rules", "Keep night/day availability explicit.", "Clock Note"],
    ["Mentor Value", "Make training useful beyond tutorial flow.", "Mentor Note"],
    ["Shop Hours", "Make shop availability readable and fair.", "Shop Note"],
    ["Hidden NPCs", "Keep hidden mentor clues tied to skills and night.", "Hidden Note"],
    ["NPC Smoke", "Guard NPC and schedule hooks.", "NPC Token"],
  ]),
  blueprint(8, "Economy And Loot Pass", "Make pickups, shops, and rewards coherent.", [
    ["Loot Table", "Review destructible and map loot sources.", "Loot Chip"],
    ["Shop Identity", "Give regional shops distinct inventory.", "Shop Chip"],
    ["Item Effects", "Keep item effects obvious and useful.", "Item Chip"],
    ["Reward Scale", "Balance XP, coins, and stage rewards.", "Coin Chip"],
    ["Economy Smoke", "Guard item/shop hooks.", "Economy Token"],
  ]),
  blueprint(9, "Figurine Tactics Pass", "Strengthen the collectible tactics minigame.", [
    ["Collection UI", "Make collected figures easier to review.", "Figure Card"],
    ["Type Roles", "Clarify Strike, Blast, Guard, Trick, and Spirit.", "Type Card"],
    ["Spawn Logic", "Tie figurines to zone, weather, and story state.", "Spawn Card"],
    ["Duel Rewards", "Reward victories without breaking economy balance.", "Duel Card"],
    ["Figurine Smoke", "Guard tactics minigame hooks.", "Figure Token"],
  ]),
  blueprint(10, "Aura Forge Pass", "Make crafting feel skillful, not random.", [
    ["Timing Loop", "Keep forge timing readable in a modal canvas.", "Forge Ring"],
    ["Reward Bands", "Make forge success tiers visible.", "Forge Band"],
    ["Failure Softness", "Avoid hard failure for missed timing.", "Forge Patch"],
    ["Audio Feedback", "Make success and failure sounds distinct.", "Forge Tone"],
    ["Forge Smoke", "Guard forge minigame hooks.", "Forge Token"],
  ]),
  blueprint(11, "Sky Courier Pass", "Make 2.5D flight routes earn their place.", [
    ["Altitude Feel", "Improve lane movement and wind meaning.", "Sky Lane"],
    ["Hazard Readability", "Make mines, clouds, and routes visible.", "Sky Flare"],
    ["Cargo Stakes", "Reward clean delivery with useful items.", "Cargo Tag"],
    ["Route Unlocks", "Tie flight routes to campaign progress.", "Flight Tag"],
    ["Courier Smoke", "Guard flight and courier hooks.", "Courier Token"],
  ]),
  blueprint(12, "Audio Stage Pass", "Give every state a sound identity.", [
    ["SFX Coverage", "Audit action, UI, weather, loot, and combat events.", "Sound Note"],
    ["Music Layers", "Keep location, encounter, and boss loops distinct.", "Music Note"],
    ["Weather Sound", "Make weather transitions audible.", "Weather Tone"],
    ["Volume Future", "Plan mixer controls without overbuilding.", "Mixer Note"],
    ["Audio Smoke", "Guard sound and music functions.", "Audio Token"],
  ]),
  blueprint(13, "Accessibility Pass", "Keep the game playable for more hands and screens.", [
    ["Readable Panels", "Keep HUD text compact and non-overlapping.", "Read Tag"],
    ["Input Redundancy", "Support keyboard and controller for core flows.", "Input Tag"],
    ["Modal Focus", "Keep focus movement predictable.", "Focus Tag"],
    ["Color Meaning", "Avoid relying only on aura color for state.", "Color Tag"],
    ["Access Smoke", "Guard controller and UI hooks.", "Access Token"],
  ]),
  blueprint(14, "Performance Pass", "Keep the single-file renderer responsive.", [
    ["Draw Budget", "Limit per-frame work to visible map slices.", "Frame Tag"],
    ["Generated Maps", "Cache generated maps after first creation.", "Cache Tag"],
    ["Audio Budget", "Keep procedural audio simple and event-driven.", "Audio Tag"],
    ["DOM Budget", "Update HUD without creating huge layouts.", "DOM Tag"],
    ["Perf Smoke", "Guard launch files and smoke checks.", "Perf Token"],
  ]),
  blueprint(15, "GitHub Pages Pass", "Make the hosted build clean and self-describing.", [
    ["Static Root", "Serve the browser game from the repository root.", "Pages Tag"],
    ["No Jekyll", "Keep GitHub Pages from filtering static files.", "Pages Note"],
    ["Hosted Link", "Document the published URL.", "URL Note"],
    ["Offline Shape", "Keep runtime free of dependency installs.", "Offline Tag"],
    ["Deploy Smoke", "Guard launch files before push.", "Deploy Token"],
  ]),
  blueprint(16, "Lore And Codex Pass", "Make original worldbuilding easier to discover.", [
    ["Faction Notes", "Summarize Ember, Shrine, and Rift identities.", "Lore Page"],
    ["Region Notes", "Give each map a short purpose.", "Region Page"],
    ["Technique Notes", "Explain hidden techniques without spoilers.", "Technique Page"],
    ["Boss Notes", "Tie bosses to world stakes.", "Boss Page"],
    ["Lore Smoke", "Guard blueprint and lore surfaces.", "Lore Token"],
  ]),
  blueprint(17, "Training Systems Pass", "Make non-combat progression matter.", [
    ["Mentor Training", "Keep trainers useful for XP, spirit, and skill growth.", "Training Tag"],
    ["Weather Training", "Reward risky training in storms.", "Storm Tag"],
    ["Form Mastery", "Plan mastery rewards around drain and identity.", "Mastery Tag"],
    ["Hidden Trials", "Tie secret techniques to skill-gated perception.", "Trial Tag"],
    ["Training Smoke", "Guard mentor/training hooks.", "Training Token"],
  ]),
  blueprint(18, "Branching Story Pass", "Make choices create visible ripples.", [
    ["Faction Bonus", "Keep branch rewards distinct but not mandatory.", "Branch Tag"],
    ["Quest Echo", "Show branch state in the quest log and HUD.", "Echo Tag"],
    ["Boss Outcome", "Plan boss consequences per route.", "Outcome Tag"],
    ["Final Route", "Tie final route to faction reputation later.", "Final Tag"],
    ["Branch Smoke", "Guard branch state hooks.", "Branch Token"],
  ]),
  blueprint(19, "QA And Regression Pass", "Make the project safer to keep expanding.", [
    ["Smoke Coverage", "Expand checks when systems are added.", "Smoke Tag"],
    ["Syntax Gate", "Keep `node --check` in the regular loop.", "Syntax Tag"],
    ["Content Counts", "Guard objective and blueprint counts.", "Count Tag"],
    ["Pages Check", "Validate local and hosted entry points.", "Page Tag"],
    ["QA Smoke", "Run the full smoke suite.", "QA Token"],
  ]),
  blueprint(20, "Next-Slice Production Pass", "Turn this prototype into a repeatable content pipeline.", [
    ["Slice Contract", "Define the next playable slice before adding bulk content.", "Slice Tag"],
    ["Data Boundaries", "Move repeatable content into structured modules.", "Data Tag"],
    ["Authoring Loop", "Use Brain query/mine/sync around each stage.", "Brain Tag"],
    ["Playable Review", "Keep browser validation at the end of every cycle.", "Review Tag"],
    ["Production Smoke", "Guard all new blueprint data.", "Production Token"],
  ]),
];

function blueprint(cycle, title, focus, stageRows) {
  return {
    cycle,
    title,
    focus,
    stages: stageRows.map(([name, work, reward], index) => ({
      index: index + 1,
      name,
      query: `${title.toLowerCase()} stage ${index + 1} ${name.toLowerCase()}`,
      work,
      reward,
    })),
  };
}
